version: "3"
services:
  # DB // Cache
  redis:
    image: redis

  # Backend
  api:
    image: maven:3.3.3-jdk-8
    command: mvn clean spring-boot:run
    volumes:
      - ~/.m2:/root/.m2
      - ./back/:/usr/src/app
    working_dir: /usr/src/app

  # Frontend
  front:
    build: front/
    ports:
      - "80:3000"
    volumes:
      - ./front/static/:/usr/src/app/static/
